export const OCR_INFORMATION: string = "OCR_INFORMATION";

export const UPDATE_INFORMATION: string = "UPDATE_INFORMATION";
export const UPDATE_INFORMATION_OCR: string = "UPDATE_INFORMATION_OCR";

export const UPDATE_RELATIONSHIP: string = "UPDATE_RELATIONSHIP";
export const UPDATE_LOAN_PRODUCTS_INFOR: string = "UPDATE_LOAN_PRODUCTS_INFOR";

export const GET_INFORMATION: string = "GET_INFORMATION";
export const CHECK_ADDRESS: string = "CHECK_ADDRESS";

export const UPDATE_PRODUCT_REGISTER_INFO: string =
  "UPDATE_PRODUCT_REGISTER_INFO";

export const UPDATE_DETAIL_PRODUCT: string = "UPDATE_DETAIL_PRODUCT";
export const UPDATE_BILLING_INFORMATION: string = "UPDATE_BILLING_INFORMATION";

export const CLEAR_CUSTOMER: string = "CLEAR_CUSTOMER";
export const UPDATE_INSURRANCE: string = "UPDATE_INSURRANCE";

export const CHECK_CUSTOMER: string = "CHECK_CUSTOMER";
